name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: build-tools
        run: sdkmanager "build-tools;29.0.3"
      - name: Add Android SDK to PATH
        run: echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH

      - name: Upload a Build Artifact (normal)
        uses: actions/upload-artifact@v2.2.1
        with:
          name:  normal
          path: build/libs/Crystal.jar